// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncroBE.Infrastructure.Data;

#nullable disable

namespace SyncroBE.Infrastructure.Migrations
{
    [DbContext(typeof(SyncroDbContext))]
    [Migration("20260221030356_AddSalesModule")]
    partial class AddSalesModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyncroBE.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("asset_name");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assignment_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("observations");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("asset", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Canton", b =>
                {
                    b.Property<int>("CantonCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("canton_code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CantonCode"));

                    b.Property<string>("CantonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("canton_name");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int")
                        .HasColumnName("province_code");

                    b.HasKey("CantonCode");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("canton", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("client_id");

                    b.Property<int?>("CantonCode")
                        .HasColumnType("int")
                        .HasColumnName("canton_code");

                    b.Property<string>("ClientElectronicInvoice")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_electronic_invoice");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_email");

                    b.Property<DateTime?>("ClientLastPurchase")
                        .HasColumnType("datetime2")
                        .HasColumnName("client_last_purchase");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_phone");

                    b.Property<int>("ClientPurchases")
                        .HasColumnType("int")
                        .HasColumnName("client_purchases");

                    b.Property<string>("ClientType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DistrictCode")
                        .HasColumnType("int")
                        .HasColumnName("district_code");

                    b.Property<string>("ExactAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exact_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int?>("ProvinceCode")
                        .HasColumnType("int")
                        .HasColumnName("province_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ClientId");

                    b.HasIndex("CantonCode");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.ClientLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LocationId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("client_location", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discount_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("discount_name");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("DiscountId");

                    b.ToTable("discount", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Distributor", b =>
                {
                    b.Property<int>("DistributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("distributor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DistributorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("distributor_code");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("DistributorId");

                    b.HasIndex("DistributorCode")
                        .IsUnique();

                    b.ToTable("distributor", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.District", b =>
                {
                    b.Property<int>("DistrictCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictCode"));

                    b.Property<int>("CantonCode")
                        .HasColumnType("int")
                        .HasColumnName("canton_code");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_name");

                    b.HasKey("DistrictCode");

                    b.HasIndex("CantonCode");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("employee_schedule", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("DistributorId")
                        .HasColumnType("int")
                        .HasColumnName("distributor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("product_price");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("product_quantity");

                    b.Property<string>("ProductType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_type");

                    b.HasKey("ProductId");

                    b.HasIndex("DistributorId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceCode"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_name");

                    b.HasKey("ProvinceCode");

                    b.ToTable("province", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<bool>("PurchasePaid")
                        .HasColumnType("bit")
                        .HasColumnName("purchase_paid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<int?>("TaxId")
                        .HasColumnType("int")
                        .HasColumnName("tax_id");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TaxId");

                    b.HasIndex("UserId");

                    b.ToTable("purchase", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quote_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("client_id");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("discount_id");

                    b.Property<string>("QuoteConditions")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("quote_conditions");

                    b.Property<string>("QuoteCustomer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quote_customer");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("quote_date");

                    b.Property<bool>("QuoteDiscountApplied")
                        .HasColumnType("bit")
                        .HasColumnName("quote_discountapplied");

                    b.Property<int>("QuoteDiscountPercentage")
                        .HasColumnType("int")
                        .HasColumnName("quote_discountpercentage");

                    b.Property<string>("QuoteDiscountReason")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("quote_discountreason");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quote_number");

                    b.Property<string>("QuoteRemarks")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("quote_remarks");

                    b.Property<string>("QuoteStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quote_status");

                    b.Property<DateTime>("QuoteValidDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("quote_validdate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("QuoteId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("QuoteNumber")
                        .HasDatabaseName("quote_number");

                    b.HasIndex("UserId");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.QuoteDetail", b =>
                {
                    b.Property<int>("QuoteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteDetailId"));

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("line_total")
                        .HasComputedColumnSql("[quantity] * [unit_price]", true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("QuoteDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("QuoteId");

                    b.ToTable("quote_detail", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.SaleDetail", b =>
                {
                    b.Property<int>("SaleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sale_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDetailId"));

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total")
                        .HasComputedColumnSql("[quantity] * [unit_price]", true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SaleDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("sale_detail", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Tax", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tax_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tax_name");

                    b.HasKey("TaxId");

                    b.ToTable("tax", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("MustChangePassword");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserLastname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_lastname");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_role");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Asset", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Canton", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Province", "Province")
                        .WithMany("Cantons")
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Client", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Canton", "Canton")
                        .WithMany("Clients")
                        .HasForeignKey("CantonCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SyncroBE.Domain.Entities.District", "District")
                        .WithMany("Clients")
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SyncroBE.Domain.Entities.Province", "Province")
                        .WithMany("Clients")
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Canton");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.ClientLocation", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Client", "Client")
                        .WithOne("Location")
                        .HasForeignKey("SyncroBE.Domain.Entities.ClientLocation", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.District", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Canton", "Canton")
                        .WithMany("Districts")
                        .HasForeignKey("CantonCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Product", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Distributor", "Distributor")
                        .WithMany("Products")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Client", "Client")
                        .WithMany("Purchases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncroBE.Domain.Entities.Tax", "Tax")
                        .WithMany("Purchases")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tax");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Quote", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Client", "Client")
                        .WithMany("Quotes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncroBE.Domain.Entities.Discount", "Discount")
                        .WithMany("Quotes")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("User", "User")
                        .WithMany("Quotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.QuoteDetail", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Product", "Product")
                        .WithMany("QuoteDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncroBE.Domain.Entities.Quote", "Quote")
                        .WithMany("QuoteDetails")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.SaleDetail", b =>
                {
                    b.HasOne("SyncroBE.Domain.Entities.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncroBE.Domain.Entities.Purchase", "Purchase")
                        .WithMany("SaleDetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Canton", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Client", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("Purchases");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Discount", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Distributor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.District", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Product", b =>
                {
                    b.Navigation("QuoteDetails");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Province", b =>
                {
                    b.Navigation("Cantons");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Quote", b =>
                {
                    b.Navigation("QuoteDetails");
                });

            modelBuilder.Entity("SyncroBE.Domain.Entities.Tax", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
